# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelpost',
            name='Branch',
            field=models.CharField(choices=[('ComputerScience', 'CS'), ('i.t.', 'IT'), ('cs&it', 'CS&IT'), ('Electrical', 'EC'), ('csitec', 'CS,IT&EC'), ('mech', 'MECHANICAL'), ('civil', 'CIVIL'), ('mech&civil', 'MEC&CIVIL'), ('all', 'ALL')], default='all', max_length=2),
        ),
    ]
