# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_panelpost_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelpost',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.AddField(
            model_name='panelpost',
            name='College',
            field=models.CharField(default='Ipec', max_length=140),
        ),
        migrations.AddField(
            model_name='panelpost',
            name='Markslow12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panelpost',
            name='Markslowb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panelpost',
            name='Pack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panelpost',
            name='Training',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='panelpost',
            name='Branch',
            field=models.CharField(choices=[('ComputerScience', 'CS'), ('i.t.', 'IT'), ('cs&it', 'CS&IT'), ('Electrical', 'EC'), ('csitec', 'CS,IT&EC'), ('mech', 'MECHANICAL'), ('civil', 'CIVIL'), ('mech&civil', 'MEC&CIVIL'), ('all', 'ALL')], default='all', max_length=200),
        ),
        migrations.AlterField(
            model_name='panelpost',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 7, 0, 46, 56, 797050)),
        ),
    ]
