# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171207_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelpost',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 7, 1, 31, 49, 27711)),
        ),
    ]
