# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171207_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelpost',
            name='Type',
            field=models.CharField(choices=[('ComputerScience', 'CS'), ('i.t.', 'IT'), ('cs&it', 'CS&IT'), ('Electrical', 'EC'), ('csitec', 'CS,IT&EC'), ('mech', 'MECHANICAL'), ('civil', 'CIVIL'), ('mech&civil', 'MEC&CIVIL'), ('all', 'ALL')], default='notice', max_length=200),
        ),
        migrations.AlterField(
            model_name='panelpost',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 0, 36, 46, 693041)),
        ),
    ]
