# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-08 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171208_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 21, 25, 4, 42573)),
        ),
        migrations.AlterField(
            model_name='panelpost',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 21, 25, 4, 42074)),
        ),
        migrations.AlterField(
            model_name='panelpost',
            name='Type',
            field=models.CharField(choices=[('placement', 'placement'), ('congractulations', 'congratulations'), ('list_of_students', 'list_of_students'), ('notice', 'notice')], default='notice', max_length=200),
        ),
    ]
