# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-10 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20171208_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelpost',
            name='DDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 11, 0, 32, 14, 883921)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 11, 0, 32, 14, 885939)),
        ),
        migrations.AlterField(
            model_name='panelpost',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 11, 0, 32, 14, 883921)),
        ),
    ]
