# Generated by Django 2.0.2 on 2018-03-09 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171211_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(choices=[('ComputerScience', 'CS'), ('i.t.', 'IT'), ('Electrical', 'EC'), ('mech', 'MECHANICAL'), ('civil', 'CIVIL'), ('all', 'ALL')], default='all', max_length=200)),
                ('ListName', models.CharField(max_length=140)),
                ('College', models.CharField(default='Ipec', max_length=140)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 10, 0, 58, 59, 948467))),
                ('Markslow12', models.IntegerField(default=0)),
                ('Markslowb', models.IntegerField(default=0)),
                ('Markslowc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=140)),
                ('rollno', models.IntegerField(default=0)),
                ('Branch', models.CharField(choices=[('ComputerScience', 'CS'), ('i.t.', 'IT'), ('Electrical', 'EC'), ('mech', 'MECHANICAL'), ('civil', 'CIVIL'), ('all', 'ALL')], default='all', max_length=200)),
                ('Markslow12', models.IntegerField(default=0)),
                ('Markslowc', models.IntegerField(default=0)),
                ('Markslowb', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 10, 0, 58, 59, 948467)),
        ),
        migrations.AlterField(
            model_name='panelpost',
            name='DDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 10, 0, 58, 59, 948467)),
        ),
        migrations.AlterField(
            model_name='panelpost',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 10, 0, 58, 59, 948467)),
        ),
    ]
