# Generated by Django 2.0.2 on 2018-03-19 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180319_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 19, 12, 19, 33, 349277)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 19, 12, 19, 33, 349277)),
        ),
        migrations.AlterField(
            model_name='panelpost',
            name='DDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 19, 12, 19, 33, 349277)),
        ),
        migrations.AlterField(
            model_name='panelpost',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 19, 12, 19, 33, 349277)),
        ),
    ]
